//! Library file with functions consuming protobufs generated by another library

use proto_generator::export::GenericRequest;
use protobuf::SpecialFields;
use protobuf_json_mapping;

pub fn show_consumed_proto() {
    let example_request = GenericRequest {
        header: Some("foo header".to_string()),
        body: Some("bar body".to_string()),
        special_fields: SpecialFields::default(),
    };
    let example_request_serialized_json = protobuf_json_mapping::print_to_string(&example_request)
        .unwrap();
    println!("{}", example_request_serialized_json)
}
